import express from 'express';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import process from 'node:process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();
const port = process.env.PORT || 3000;
const staticDir = join(__dirname, 'docs');
const basePath = '/CreFlux';

app.disable('x-powered-by');

// Serve the production build generated by Vite.
app.use(basePath, express.static(staticDir));
app.use(express.static(staticDir));

// Handles any requests that don't match the ones above
app.use((req, res) => {
    res.sendFile(join(staticDir, 'index.html'));
});

app.listen(port, () => {
    console.log(`Server listening on port ${port}`);
});
